# Generated by Django 6.0.6 on 2026-07-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Jarayonda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='aigeneration',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
